- name: Create data folder
  file:
    path: /data
    state: directory

- name: Uninstall swapfile
  command: dphys-swapfile uninstall

- name: Copy fstab
  copy:
    src: 'etc/fstab'
    dest: '/etc/fstab'

- name: Mount data directory
  mount:
    src: /dev/mmcblk0p3
    path: /data
    fstype: ext4
    state: mounted

- name: Create dhcp directory
  file:
    path: /data/dhcp
    state: directory

- name: Create dhcpcd directory
  file:
    path: /data/dhcpcd
    state: directory

- name: Remove old dhcp folder
  file:
    path: /var/lib/dhcp
    state: absent

- name: Remove old dhcpcd folder
  file:
    path: /var/lib/dhcpcd
    state: absent

- name: Create dhcp directory symbolic link
  file:
    src: /data/dhcp
    dest: /var/lib/dhcp
    state: link

- name: Create dhcpcd directory symbolic link
  file:
    src: /data/dhcpcd
    dest: /var/lib/dhcpcd
    state: link

- name: Copy systemd-journald configuration
  copy:
    src: 'etc/systemd/journald.conf.d/lantern.conf'
    dest: '/etc/systemd/journald.conf.d/lantern.conf'

- name: Restart systemd-journald service
  systemd:
    name: systemd-journald
    state: restarted

- name: Add gpg key for nodejs
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    keyring: /etc/apt/keyrings/nodesource.gpg

- name: Add nodejs repository
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main
    state: present

- name: Install needed packages
  apt:
    update_cache: yes
    state: latest
    pkg:
        - mc
        - apt-show-versions
        - nginx
        - php-fpm
        - wakeonlan
        - mosquitto
        - mosquitto-clients
        - git
        - make
        - g++
        - gcc
        - nodejs
        - libmosquitto-dev
        - libjansson-dev

- name: Set hostname
  hostname:
    name: '{{ ansible_host }}'

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\s+'
    line: '127.0.1.1       {{ ansible_host }}'

- name: Configure the locale
  lineinfile:
    path: /etc/locale.gen
    regexp: '^#? *da_DK\.UTF-8 UTF-8$'
    line: 'da_DK.UTF-8 UTF-8'

- name: Configure da_DK.UTF-8 locale
  command: locale-gen

- name: Set timezone
  community.general.timezone:
    name: Europe/Copenhagen
